[tools]
chezmoi = "latest"
go = "latest"
node = "latest"
"github:JohnnyMorganz/stylua" = "latest"
lua-language-server = "latest"
"mason:vscode-css-language-server" = "latest"
"mason:tailwindcss-language-server" = "latest"
"npm:prettier" = "latest"
"mason:typescript-language-server" = "latest"
yamlfmt = "latest"
gofumpt = "latest"
"npm:intelephense" = "latest"
tree-sitter = "latest"
bob = "latest"
rust = "latest"
opencode = "latest"
golangci-lint-langserver = "latest"
gitui = "latest"
golangci-lint = "latest"
marksman = "latest"
"npm:fish-lsp" = "latest"
"go:github.com/go-delve/delve/cmd/dlv" = "latest"
lua = "latest"

[settings]
experimental = true
